
"""
A program that reads a playfair encrypted cipher_text
and a key and decrypts the cipher_text.
"""


def matrix(x: int, y: int, initial: int) -> list[list[int]]:
    """ Generate a matrix with the x and y parameters
    as the no. of rows and columns of the matrix generated
    initialized with the int initial.

    """

    return [[initial for _ in range(x)] for _ in range(y)]


def key_in_mat(a: int, b: int, key: str) -> list[list[int]]:
    """ Fills in the matrix generated by the matrix function
    above with the appropriate character value indices.

    """

    key_into_matrix: list = []

    for char in key:
        if char not in key_into_matrix:
            if char == 'J':
                key_into_matrix.append('I')
            else:
                key_into_matrix.append(char)

    # this fills in the rest of the matrix with the remaining unused letters
    # from the english alphabet

    for i in range(65, 91):
        if chr(i) not in key_into_matrix:

            if i == 73 and chr(74) not in key_into_matrix:
                key_into_matrix.append("I")

                a = 1

            elif a == 0 and i == 73 or i == 74:
                pass

            else:
                key_into_matrix.append(chr(i))

    # defining the cipher matrix as a 5x5 matrix with an inital of 0

    cipher_matrix: list[list[int]] = matrix(5, 5, 0)

    for i in range(0, 5):
        for j in range(0, 5):
            cipher_matrix[i][j] = key_into_matrix[b]

            b += 1

    return cipher_matrix


def index_locator(cipher_matrix: list[list[int]], x: str) -> list[int]:
    """Replaces every instance of the character J with
    an I according to the rules of the playfair cypher
    encryption. It also adds the rest of the letters indices
    to alist and returns the list...

    """
    lst: list = []

    if x == 'J':
        x = 'I'

    for i, j in enumerate(cipher_matrix):

        for k, l in enumerate(j):
            if x == l:
                lst.append(i)
                lst.append(k)

    return lst


def decryption(ciphermatrix: list[list[int]], text: str) -> None:
    i: int = 0
    for s in range(0, len(text)+1, 2):

        if s < len(text)-1:
            if text[s] == text[s+1]:
                text = text[:s+1]+'X'+text[s+1:]

    if len(text) % 2 != 0:

        text = text[:]+'X'

    word: str = ""

    while i < len(text):
        lst = []
        lst = index_locator(ciphermatrix, text[i])
        lon = []
        lon = index_locator(ciphermatrix, text[i+1])

        if lst[1] == lon[1]:
            word += f"{ciphermatrix[(lst[0] - 1) %5][lst[1]]}\
                  {ciphermatrix[(lon[0] - 1) %5][lon[1]]}"

        elif lst[0] == lon[0]:
            word += f"{ciphermatrix[lst[0]][(lst[1] - 1) % 5]}\
                  {ciphermatrix[lon[0]][(lon[1] - 1) % 5]}"

        else:
            word += f"{ciphermatrix[lst[0]][lon[1]]}\
                  {ciphermatrix[lon[0]][lst[1]]}"

        i += 2

    word: str = "".join(char for char in word
                        if not char.isspace())

    print(word)


def main():

    a: int = 0
    b: int = 0

    while True:
        key: str = input("Enter key: ")
        key: str = key.replace(" ", "")
        key: str = key.upper()

        if key == "":
            break

        ciphertext: str = input("Cipher text: ")
        ciphertext: str = ciphertext.replace(" ", "")
        ciphertext: str = ciphertext.upper()

        if ciphertext == "":
            break

        ciphermatrix = key_in_mat(a, b, key)
        decryption(ciphermatrix, ciphertext)


if __name__ == '__main__':
    main()
